import { apiErrorSchema, aiOutputSchema, apiResponseSchema } from "./api";
import {
  claimSchema,
  constraintSchema,
  evidenceSchema,
  generatedAssetSchema,
  generatedComponentSchema,
  projectSchema,
  provenanceRecordSchema,
  releasePassportSchema,
  repairActionSchema,
  sourceAssetSchema,
  sponsorRequirementSchema,
  transcriptSegmentSchema,
  verificationFindingSchema,
  verificationRunSchema,
  workflowStateSchema,
} from "./domain";

export const FROZEN_CONTRACTS = [
  "Project",
  "SourceAsset",
  "TranscriptSegment",
  "Claim",
  "Evidence",
  "GeneratedAsset",
  "GeneratedComponent",
  "VerificationRun",
  "VerificationFinding",
  "WorkflowState",
  "Constraint",
  "SponsorRequirement",
  "RepairAction",
  "ReleasePassport",
  "ProvenanceRecord",
  "APIResponse",
  "AiOutput",
  "ApiError",
] as const;

export const DEFERRED_CONTRACTS = [
  { name: "PerformanceObservation", targetWave: "later" },
  { name: "LearningRecord", targetWave: "later" },
] as const;

export const CONTRACTS = {
  Project: projectSchema,
  SourceAsset: sourceAssetSchema,
  TranscriptSegment: transcriptSegmentSchema,
  Claim: claimSchema,
  Evidence: evidenceSchema,
  GeneratedAsset: generatedAssetSchema,
  GeneratedComponent: generatedComponentSchema,
  VerificationRun: verificationRunSchema,
  VerificationFinding: verificationFindingSchema,
  WorkflowState: workflowStateSchema,
  Constraint: constraintSchema,
  SponsorRequirement: sponsorRequirementSchema,
  RepairAction: repairActionSchema,
  ReleasePassport: releasePassportSchema,
  ProvenanceRecord: provenanceRecordSchema,
  APIResponse: apiResponseSchema,
  AiOutput: aiOutputSchema,
  ApiError: apiErrorSchema,
} as const;